use asterisk;
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('activated','activated','Activated.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('added','added','Added.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('agent-alreadyon','agent-alreadyon','That\ agent\ is\ already\ logged\ on.\ \ Please\ enter\ your\ agent\ number\ followed\ by\ the\ pound\ key.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('agent-incorrect','agent-incorrect','Login\ incorrect.\ \ Please\ enter\ your\ agent\ number\ followed\ by\ the\ pound\ key.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('agent-loggedoff','agent-loggedoff','Agent\ Logged\ off.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('agent-loginok','agent-loginok','Agent\ logged\ in.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('agent-newlocation','agent-newlocation','Please\ enter\ a\ new\ extension\,\ followed\ by\ pound.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('agent-pass','agent-pass','Please\ enter\ your\ password\ followed\ by\ the\ pound\ key.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('agent-user','agent-user','Agent\ login.\ \ Please\ enter\ your\ agent\ number\ followed\ by\ the\ pound\ key.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('all-circuits-busy-now','all-circuits-busy-now','All\ circuits\ are\ busy\ now.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('astcc-followed-by-pound','astcc-followed-by-pound','Followed\ by\ the\ pound\ key.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('at-tone-time-exactly','at-tone-time-exactly','At\ the\ sound\ of\ the\ tone\,\ the\ time\ will\ be\ exactly...',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('auth-incorrect','auth-incorrect','Password\ incorrect.\ \ Please\ enter\ your\ password\ followed\ by\ the\ pound\ key.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('auth-thankyou','auth-thankyou','Thank\ you.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('basic-pbx-ivr-main','basic-pbx-ivr-main','Thank\ you\ for\ calling\ Super\ Awesome\ Company\,\ Waldo\'s\ premier\ provider\ of\ perfect\ products.\ If\ you\ know\ your\ party\'s\ extension\,\ you\ may\ dial\ it\ at\ any\ time.\ To\ establish\ a\ sales\ partnership\,\ press\ one.\ To\ speak\ with\ a\ customer\ advocate\,\ press\ two.\ For\ accounting\ and\ other\ receivables\,\ press\ three.\ For\ a\ company\ directory\,\ press\ four.\ For\ an\ operator\,\ press\ zero.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('call-forwarding','call-forwarding','Call\ forwarding.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('call-fwd-no-ans','call-fwd-no-ans','Call-Forward\ on\ No\ Answer.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('call-fwd-on-busy','call-fwd-on-busy','Call-Forward\ on\ Busy.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('call-fwd-unconditional','call-fwd-unconditional','Call-Forward\ Unconditional.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('calling','calling','Calling.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('call-waiting','call-waiting','Call\ waiting.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('cancelled','cancelled','Cancelled.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('cannot-complete-as-dialed','cannot-complete-as-dialed','Your\ call\ cannot\ be\ completed\ as\ dialed.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('check-number-dial-again','check-number-dial-again','Please\ check\ the\ number\ and\ dial\ again.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('conf-adminmenu-162','conf-adminmenu-162','Please\ press\ 1\ to\ mute\ or\ unmute\ yourself\,\ 2\ to\ lock\ or\ unlock\ the\ conference\,\ 3\ to\ eject\ the\ last\ user\,\ 4\ or\ 6\ to\ decrease\ or\ increase\ the\ conference\ volume\,\ 5\ to\ extend\ the\ conference\,\ 7\ or\ 9\ to\ decrease\ or\ increase\ your\ volume\,\ or\ 8\ to\ exit.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('conf-adminmenu-18','conf-adminmenu-18','Please\ press\ 1\ to\ mute\ or\ unmute\ yourself\,\ 2\ to\ lock\ or\ unlock\ the\ conference\,\ 3\ to\ eject\ the\ last\ user\,\ 4\ or\ 6\ to\ decrease\ or\ increase\ the\ conference\ volume\,\ 5\ to\ extend\ the\ conference\,\ 7\ or\ 9\ to\ decrease\ or\ increase\ your\ volume\,\ or\ 8\ for\ more\ options.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('conf-adminmenu-menu8','conf-adminmenu-menu8','Press\ 1\ to\ list\ users\ currently\ in\ the\ conference\,\ 2\ to\ kick\ all\ non-administrator\ users\,\ 3\ to\ mute\ or\ umute\ all\ non-administrator\ users\,\ 4\ to\ record\ this\ conference\,\ or\ 8\ to\ exit\ this\ menu\ and\ return\ to\ the\ conference.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('conf-adminmenu','conf-adminmenu','Please\ press\ 1\ to\ mute\ or\ unmute\ yourself\,\ 2\ to\ lock\ or\ unlock\ the\ conference\,\ 3\ to\ eject\ the\ last\ user\,\ 4\ or\ 6\ to\ decrease\ or\ increase\ the\ conference\ volume\,\ 7\ or\ 9\ to\ decrease\ or\ increase\ your\ volume\,\ or\ 8\ to\ exit.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('confbridge-begin-glorious-a','confbridge-begin-glorious-a','the\ conference\ will\ begin\ when\ our\ glorious\ leader\ arrives',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('confbridge-begin-glorious-b','confbridge-begin-glorious-b','the\ conference\ will\ begin\ when\ our\ glorious\ leader\ arrives',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('confbridge-begin-glorious-c','confbridge-begin-glorious-c','the\ conference\ will\ begin\ when\ our\ glorious\ leader\ arrives',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('confbridge-begin-leader','confbridge-begin-leader','the\ conference\ will\ begin\ when\ the\ leader\ arrives',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('confbridge-conf-begin','confbridge-conf-begin','the\ conference\ will\ now\ begin',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('confbridge-conf-end','confbridge-conf-end','the\ conference\ has\ ended',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('confbridge-dec-list-vol-in','confbridge-dec-list-vol-in','To\ decrease\ the\ audio\ volume\ from\ other\ participants...',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('confbridge-dec-list-vol-out','confbridge-dec-list-vol-out','...to\ decrease\ the\ audio\ volume\ from\ other\ participants.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('confbridge-dec-talk-vol-in','confbridge-dec-talk-vol-in','To\ decrease\ your\ speaking\ volume\ to\ other\ participants...',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('confbridge-dec-talk-vol-out','confbridge-dec-talk-vol-out','...to\ decrease\ your\ speaking\ volume\ to\ other\ participants.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('confbridge-has-joined','confbridge-has-joined','...has\ joined\ the\ conference.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('confbridge-has-left','confbridge-has-left','...has\ left\ the\ conference.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('confbridge-inc-list-vol-in','confbridge-inc-list-vol-in','To\ increase\ the\ audio\ volume\ from\ other\ participants...',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('confbridge-inc-list-vol-out','confbridge-inc-list-vol-out','...to\ increase\ the\ audio\ volume\ from\ other\ participants.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('confbridge-inc-talk-vol-in','confbridge-inc-talk-vol-in','To\ increase\ your\ speaking\ volume\ to\ other\ participants...',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('confbridge-inc-talk-vol-out','confbridge-inc-talk-vol-out','...to\ increase\ your\ speaking\ volume\ to\ other\ participants.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('confbridge-invalid','confbridge-invalid','You\ have\ entered\ an\ invalid\ option.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('confbridge-leave-in','confbridge-leave-in','To\ leave\ the\ conference...',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('confbridge-leave-out','confbridge-leave-out','...to\ leave\ the\ conference.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('confbridge-locked','confbridge-locked','The\ conference\ is\ now\ locked.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('confbridge-lock-extended','confbridge-lock-extended','...to\ lock\,\ or\ unlock\ the\ conference.\ When\ a\ conference\ is\ locked\ only\ conference\ administrators\ can\ join.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('confbridge-lock-in','confbridge-lock-in','To\ lock\,\ or\ unlock\ the\ conference...',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('confbridge-lock-no-join','confbridge-lock-no-join','The\ conference\ is\ currently\ locked\ and\ cannot\ be\ joined.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('confbridge-lock-out','confbridge-lock-out','...to\ lock\,\ or\ unlock\ the\ conference.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('confbridge-menu-exit-in','confbridge-menu-exit-in','To\ exit\ the\ menu...',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('confbridge-menu-exit-out','confbridge-menu-exit-out','...to\ exit\ the\ menu.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('confbridge-muted','confbridge-muted','You\ are\ now\ muted.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('confbridge-mute-extended','confbridge-mute-extended','...to\ mute\,\ or\ unmute\ yourself.\ When\ you\ are\ muted\ you\ can\ not\ send\ audio\ to\ other\ participants.\ However\ you\ will\ still\ hear\ audio\ from\ other\ unmuted\ participants.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('confbridge-mute-in','confbridge-mute-in','To\ mute\ or\ unmute\ yourself...',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('confbridge-mute-out','confbridge-mute-out','...to\ mute\ or\ unmute\ yourself.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('confbridge-only-one','confbridge-only-one','There\ is\ currently\ one\ other\ participant\ in\ the\ conference.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('confbridge-only-participant','confbridge-only-participant','You\ are\ currently\ the\ only\ participant\ in\ the\ conference.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('confbridge-participants','confbridge-participants','...participants\ in\ the\ conference.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('confbridge-pin-bad','confbridge-pin-bad','You\ have\ entered\ too\ many\ invalid\ personal\ identification\ numbers.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('confbridge-pin','confbridge-pin','Please\ enter\ your\ personal\ identification\ number\ followed\ by\ the\ pound\,\ or\ hash\ key.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('confbridge-removed','confbridge-removed','You\ have\ been\ removed\ from\ the\ conference.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('confbridge-remove-last-in','confbridge-remove-last-in','To\ remove\ the\ participant\ who\ most\ recently\ joined\ the\ conference...',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('confbridge-remove-last-out','confbridge-remove-last-out','...to\ remove\ the\ participant\ who\ most\ recently\ joined\ the\ conference.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('confbridge-rest-list-vol-in','confbridge-rest-list-vol-in','To\ reset\ the\ audio\ volume\ of\ the\ conference\ to\ the\ default\ level...',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('confbridge-rest-list-vol-out','confbridge-rest-list-vol-out','...to\ reset\ the\ audio\ volume\ of\ the\ conference\ to\ the\ default\ level.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('confbridge-rest-talk-vol-in','confbridge-rest-talk-vol-in','To\ reset\ your\ speaking\ volume\ to\ the\ default\ level...',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('confbridge-rest-talk-vol-out','confbridge-rest-talk-vol-out','...to\ reset\ your\ speaking\ volume\ to\ the\ default\ level.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('confbridge-there-are','confbridge-there-are','There\ are\ currently...',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('confbridge-unlocked','confbridge-unlocked','The\ conference\ is\ now\ unlocked.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('confbridge-unmuted','confbridge-unmuted','You\ are\ no\ longer\ muted.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('conf-enteringno','conf-enteringno','You\ are\ entering\ conference\ number',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('conf-errormenu','conf-errormenu','Invalid\ Choice',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('conf-extended','conf-extended','The\ conference\ has\ been\ extended.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('conf-full','conf-full','That\ conference\ is\ full.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('conf-getchannel','conf-getchannel','Please\ enter\ the\ channel\ number\ followed\ by\ the\ pound\ key.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('conf-getconfno','conf-getconfno','Please\ enter\ your\ conference\ number\ followed\ by\ the\ pound\ key.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('conf-getpin','conf-getpin','Please\ enter\ the\ conference\ pin\ number.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('conf-hasjoin','conf-hasjoin','is\ now\ in\ the\ conference.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('conf-hasleft','conf-hasleft','has\ left\ the\ conference.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('conf-invalidpin','conf-invalidpin','That\ pin\ is\ invalid\ for\ this\ conference.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('conf-invalid','conf-invalid','That\ is\ not\ a\ valid\ conference\ number.\ \ Please\ try\ again.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('conf-kicked','conf-kicked','You\ have\ been\ kicked\ from\ this\ conference',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('conf-leaderhasleft','conf-leaderhasleft','The\ leader\ has\ left\ the\ conference.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('conf-lockednow','conf-lockednow','The\ conference\ is\ now\ locked',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('conf-locked','conf-locked','This\ conference\ is\ locked\!',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('conf-muted','conf-muted','You\ are\ now\ muted',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('conf-noempty','conf-noempty','No\ empty\ conferences\ currently\ exist.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('conf-nonextended','conf-nonextended','The\ conference\ cannot\ be\ extended.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('conf-now-muted','conf-now-muted','The\ conference\ is\ now\ muted.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('conf-now-recording','conf-now-recording','The\ conference\ is\ now\ being\ recorded.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('conf-now-unmuted','conf-now-unmuted','The\ conference\ is\ now\ unmuted.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('conf-onlyone','conf-onlyone','There\ is\ currently\ one\ other\ participant\ in\ the\ conference.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('conf-onlyperson','conf-onlyperson','You\ are\ currently\ the\ only\ person\ in\ this\ conference.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('conf-otherinparty','conf-otherinparty','other\ participants\ in\ the\ conference',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('conf-placeintoconf','conf-placeintoconf','You\ will\ now\ be\ placed\ into\ the\ conference.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('conf-roll-callcomplete','conf-roll-callcomplete','Playback\ of\ the\ list\ of\ people\ attending\ is\ complete.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('conf-thereare','conf-thereare','There\ are\ currently',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('conf-unlockednow','conf-unlockednow','The\ conference\ is\ now\ unlocked',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('conf-unmuted','conf-unmuted','You\ are\ now\ unmuted',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('conf-usermenu-162','conf-usermenu-162','Please\ press\ 1\ to\ mute\ or\ unmute\ yourself\,\ 4\ or\ 6\ to\ decrease\ or\ increase\ the\ conference\ volume\,\ 5\ to\ extend\ the\ conference\,\ 7\ or\ 9\ to\ decrease\ or\ increase\ your\ volume\,\ or\ 8\ to\ exit\ this\ menu\ and\ return\ to\ the\ conference.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('conf-usermenu','conf-usermenu','Please\ press\ 1\ to\ mute\ or\ unmute\ yourself\,\ 4\ or\ 6\ to\ decrease\ or\ increase\ the\ conference\ volume\,\ 7\ or\ 9\ to\ decrease\ or\ increase\ your\ volume\,\ or\ 8\ to\ exit.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('conf-userswilljoin','conf-userswilljoin','users\ will\ join\ the\ conference.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('conf-userwilljoin','conf-userwilljoin','user\ will\ join\ the\ conference.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('conf-waitforleader','conf-waitforleader','The\ conference\ will\ begin\ when\ the\ leader\ arrives.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('de-activated','de-activated','De-activated.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('demo-abouttotry','demo-abouttotry','I\ am\ about\ to\ attempt\ an\ Inter-Asterisk\ Exchange\ connection\ to\ a\ demonstration\ server\ located\ at\ Digium.\ \ In\ order\ for\ this\ to\ work\ you\ must\ already\ be\ connected\ to\ the\ Internet.\ \ Please\ wait\ a\ moment\ while\ I\ attempt\ to\ make\ the\ connection.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('demo-congrats','demo-congrats','Congratulations.\ \ You\ have\ successfully\ installed\ and\ executed\ the\ Asterisk\ open\ source\ PBX.\ \ You\ have\ also\ installed\ a\ set\ of\ sample\ sounds\ and\ configuration\ files\ that\ should\ help\ you\ to\ get\ started.\ \ Like\ a\ normal\ PBX\ you\ will\ navigate\ this\ demonstration\ by\ dialing\ digits.\ \ If\ you\ are\ using\ a\ console\ channel\ driver\ instead\ of\ a\ real\ phone\ you\ can\ use\ the\ dial\,\ answer\,\ and\ hang\ up\ commands\ to\ simulate\ the\ actions\ of\ a\ standard\ telephone.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('demo-echodone','demo-echodone','The\ echo\ test\ has\ been\ completed.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('demo-echotest','demo-echotest','You\ are\ about\ to\ enter\ an\ echo\ test.\ \ In\ this\ mode\ everything\ you\ say\ will\ be\ repeated\ back\ to\ you\ just\ as\ soon\ as\ it\ is\ received.\ \ The\ purpose\ of\ this\ test\ is\ to\ give\ you\ an\ audible\ sense\ of\ the\ latency\ between\ you\ and\ the\ machine\ that\ is\ running\ the\ echo\ test\ application.\ \ You\ may\ end\ the\ test\ by\ hanging\ up\ or\ by\ pressing\ the\ pound\ key.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('demo-enterkeywords','demo-enterkeywords','Please\ enter\ one\ or\ more\ keywords\ separated\ by\ \*\ and\ then\ press\ the\ pound\ key.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('demo-instruct','demo-instruct','If\ you\ would\ like\ to\ learn\ more\ technical\ information\ about\ Asterisk\ dial\ 2\ now.\ \ If\ you\'d\ like\ to\ test\ out\ the\ voice\ over\ IP\ capabilities\ of\ Asterisk\ you\ can\ dial\ 500\ to\ attempt\ an\ Inter-Asterisk\ Exchange\ or\ IAX\ connection\ to\ a\ demonstration\ server\ at\ Digium.\ \ In\ order\ for\ this\ test\ to\ work\ you\ will\ need\ to\ be\ connected\ to\ the\ Internet\ and\ have\ at\ least\ a\ 28.8\ kilobit\ modem.\ \ To\ execute\ an\ echo\ test\ dial\ 600.\ \ This\ test\ is\ most\ useful\ when\ you\ have\ connected\ to\ this\ Asterisk\ server\ from\ a\ remote\ location.\ \ The\ sample\ configuration\ also\ has\ a\ single\ user\ with\ extension\ 1234\ and\ password\ 4242.\ \ That\ user\ is\ configured\ to\ ring\ the\ console\ when\ their\ extension\ is\ dialed.\ \ If\ you\ dial\ 1234\ you\ can\ try\ to\ ring\ the\ console.\ \ If\ the\ console\ is\ busy\ or\ unavailable\ you\ will\ be\ given\ the\ option\ to\ leave\ voicemail.\ \ To\ check\ voice\ mail\ for\ the\ user\ dial\ extension\ 8500\ to\ enter\ the\ voicemail\ system.\ \ Finally\,\ \ you\ can\ press\ the\ pound\ key\ to\ disconnect\ from\ the\ PBX.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('demo-moreinfo','demo-moreinfo','Asterisk\ is\ an\ Open\ Source\ full-featured\ PBX\ and\ IVR\ platform\ that\ runs\ on\ the\ linux\ operating\ system.\ \ For\ more\ information\,\ visit\ www.asterisk.org.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('demo-nogo','demo-nogo','I\ am\ afraid\ I\ was\ unable\ to\ create\ a\ connection\ to\ the\ Digium\ demonstration\ Asterisk\ server.\ \ You\ may\ find\ some\ helpful\ debugging\ information\ on\ the\ Asterisk\ console.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('demo-nomatch','demo-nomatch','I\'m\ sorry\ there\ are\ no\ matches\ for\ those\ keywords',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('demo-thanks','demo-thanks','Goodbye.\ \ Thank\ you\ for\ trying\ out\ the\ Asterisk\ Open\ Source\ PBX.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('dictate/both_help','dictate/both_help','press\ \*\ to\ toggle\ pause\,\ press\ #\ to\ enter\ a\ new\ dictation\ filename',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('dictate/enter_filename','dictate/enter_filename','Enter\ a\ numeric\ dictation\ filename\ followed\ by\ #\ or\ just\ #\ to\ exit',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('dictate/forhelp','dictate/forhelp','press\ 0\ for\ help',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('dictate/paused','dictate/paused','paused',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('dictate/pause','dictate/pause','pause',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('dictate/playback_mode','dictate/playback_mode','playback\ mode',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('dictate/playback','dictate/playback','playback',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('dictate/play_help','dictate/play_help','press\ 1\ to\ switch\ to\ record\ mode\,\ press\ 2\ to\ toggle\ fast\ playback\,\ press\ 7\ to\ jump\ backwards\,\ press\ 8\ to\ jump\ forwards',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('dictate/record_help','dictate/record_help','press\ 1\ to\ switch\ to\ playback\ mode\,\ press\ 8\ to\ truncate\ the\ file\ and\ start\ over',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('dictate/record_mode','dictate/record_mode','record\ mode',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('dictate/record','dictate/record','record',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('dictate/truncating_audio','dictate/truncating_audio','truncating\ audio',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/0','digits/0','zero',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/10','digits/10','ten',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/11','digits/11','eleven',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/12','digits/12','twelve',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/13','digits/13','thirteen',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/14','digits/14','fourteen',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/15','digits/15','fifteen',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/16','digits/16','sixteen',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/17','digits/17','seventeen',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/18','digits/18','eighteen',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/19','digits/19','nineteen',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/1','digits/1','one',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/20','digits/20','twenty',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/2','digits/2','two',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/30','digits/30','thirty',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/3','digits/3','three',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/40','digits/40','forty',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/4','digits/4','four',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/50','digits/50','fifty',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/5','digits/5','five',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/60','digits/60','sixty',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/6','digits/6','six',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/70','digits/70','seventy',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/7','digits/7','seven',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/80','digits/80','eighty',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/8','digits/8','eight',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/90','digits/90','ninety',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/9','digits/9','nine',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/a-m','digits/a-m','A.M.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/at','digits/at','at',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/billion','digits/billion','billion',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/day-0','digits/day-0','Sunday',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/day-1','digits/day-1','Monday',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/day-2','digits/day-2','Tuesday',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/day-3','digits/day-3','Wednesday',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/day-4','digits/day-4','Thursday',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/day-5','digits/day-5','Friday',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/day-6','digits/day-6','Saturday',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/dollars','digits/dollars','dollars',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/h-10','digits/h-10','tenth',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/h-11','digits/h-11','eleventh',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/h-12','digits/h-12','twelfth',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/h-13','digits/h-13','thirteenth',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/h-14','digits/h-14','fourteenth',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/h-15','digits/h-15','fifteenth',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/h-16','digits/h-16','sixteenth',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/h-17','digits/h-17','seventeenth',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/h-18','digits/h-18','eighteenth',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/h-19','digits/h-19','nineteenth',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/h-1','digits/h-1','first',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/h-20','digits/h-20','twentieth',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/h-2','digits/h-2','second',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/h-30','digits/h-30','thirtieth',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/h-3','digits/h-3','third',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/h-40','digits/h-40','fourtieth',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/h-4','digits/h-4','fourth',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/h-50','digits/h-50','fiftieth',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/h-5','digits/h-5','fifth',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/h-60','digits/h-60','sixtieth',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/h-6','digits/h-6','sixth',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/h-70','digits/h-70','seventieth',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/h-7','digits/h-7','seventh',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/h-80','digits/h-80','eightieth',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/h-8','digits/h-8','eighth',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/h-90','digits/h-90','ninetieth',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/h-9','digits/h-9','ninth',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/h-billion','digits/h-billion','billionth',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/h-hundred','digits/h-hundred','hundredth',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/h-million','digits/h-million','millionth',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/h-thousand','digits/h-thousand','thousandth',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/hundred','digits/hundred','hundred',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/million','digits/million','million',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/minus','digits/minus','minus',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/mon-0','digits/mon-0','January',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/mon-10','digits/mon-10','November',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/mon-11','digits/mon-11','December',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/mon-1','digits/mon-1','February',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/mon-2','digits/mon-2','March',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/mon-3','digits/mon-3','April',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/mon-4','digits/mon-4','May',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/mon-5','digits/mon-5','June',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/mon-6','digits/mon-6','July',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/mon-7','digits/mon-7','August',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/mon-8','digits/mon-8','September',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/mon-9','digits/mon-9','October',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/oclock','digits/oclock','o\'clock',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/oh','digits/oh','oh',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/p-m','digits/p-m','P.M.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/pound','digits/pound','pound',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/star','digits/star','star',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/thousand','digits/thousand','thousand',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/today','digits/today','today',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/tomorrow','digits/tomorrow','tomorrow',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('digits/yesterday','digits/yesterday','yesterday',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('dir-firstlast','dir-firstlast','...\ letters\ of\ your\ party\'s\ first\ or\ last\ name.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('dir-first','dir-first','letters\ of\ your\ party\'s\ first\ name.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('dir-instr','dir-instr','If\ this\ is\ the\ person\ you\ are\ looking\ for\ press\ 1\ now\,\ otherwise\ please\ press\ star\ now.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('dir-intro-fn','dir-intro-fn','Welcome\ to\ the\ directory.\ \ Please\ enter\ the\ first\ three\ letters\ of\ your\ party\'s\ first\ name\ using\ your\ touch\ tone\ keypad.\ \ Use\ the\ 7\ key\ for\ Q\ and\ the\ 9\ key\ for\ Z.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('dir-intro','dir-intro','Welcome\ to\ the\ directory.\ \ Please\ enter\ the\ first\ three\ letters\ of\ your\ party\'s\ last\ name\ using\ your\ touch\ tone\ keypad.\ \ Use\ the\ 7\ key\ for\ Q\ and\ the\ 9\ key\ for\ Z.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('dir-last','dir-last','...\ letters\ of\ your\ party\'s\ last\ name.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('dir-multi1','dir-multi1','Press\ ...',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('dir-multi2','dir-multi2','...\ for\ ...',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('dir-multi3','dir-multi3','...\ extension\ ...',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('dir-multi9','dir-multi9','Press\ 9\ for\ more\ entries.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('dir-nomatch','dir-nomatch','No\ directory\ entries\ match\ your\ search.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('dir-nomore','dir-nomore','There\ are\ no\ more\ compatible\ entries\ in\ the\ directory.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('dir-pls-enter','dir-pls-enter','Please\ enter\ the\ first\ ...',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('dir-usingkeypad','dir-usingkeypad','...\ using\ your\ touchtone\ keypad.\ \ Use\ the\ 7\ key\ for\ Q\,\ and\ the\ 9\ key\ for\ Z.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('dir-welcome','dir-welcome','Welcome\ to\ the\ directory',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('disabled','disabled','Disabled.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('do-not-disturb','do-not-disturb','Do\ not\ disturb.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('enabled','enabled','Enabled.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('enter-num-blacklist','enter-num-blacklist','Please\ enter\ the\ number\ to\ be\ blacklisted.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('entr-num-rmv-blklist','entr-num-rmv-blklist','Please\ enter\ the\ number\ to\ be\ removed\ from\ the\ blacklist.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('extension','extension','Extension.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('feature-not-avail-line','feature-not-avail-line','That\ feature\ is\ not\ available\ on\ this\ line.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('followme/call-from.wav','followme/call-from.wav','incoming\ call\ from',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('followme/no-recording.wav','followme/no-recording.wav','you\ have\ an\ incoming\ call',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('followme/options.wav','followme/options.wav','press\ 1\ to\ accept\ this\ call\,\ or\ 2\ to\ reject\ it',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('followme/pls-hold-while-try.wav','followme/pls-hold-while-try.wav','please\ hold\ while\ I\ try\ to\ locate\ the\ person\ you\ are\ calling',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('followme/sorry.wav','followme/sorry.wav','I\'m\ sorry\,\ but\ I\ was\ unable\ to\ locate\ the\ person\ you\ are\ calling',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('followme/status.wav','followme/status.wav','the\ person\ you\ are\ calling\ is\ not\ at\ their\ desk\;\ I\ will\ try\ to\ locate\ them\ for\ you',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('for','for','For.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('from-unknown-caller','from-unknown-caller','From\ an\ unknown\ caller.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('goodbye','goodbye','Goodbye\!',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('hello','hello','Hello.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('hello-world','hello-world','Hello\ world.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('hours','hours','hours',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('if-correct-press','if-correct-press','If\ this\ is\ correct\,\ press...',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('im-sorry','im-sorry','I\'m\ sorry.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('info-about-last-call','info-about-last-call','Information\ about\ your\ last\ call.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('invalid','invalid','I\ am\ sorry\,\ that\'s\ not\ a\ valid\ extension.\ \ Please\ try\ again.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('is-in-use','is-in-use','Is\ in\ use.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('is','is','Is.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('is-set-to','is-set-to','Is\ set\ to.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('letters/a','letters/a','a',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('letters/ascii123','letters/ascii123','left\ brace',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('letters/ascii124','letters/ascii124','pipe',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('letters/ascii125','letters/ascii125','right\ brace',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('letters/ascii126','letters/ascii126','tilde',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('letters/ascii34','letters/ascii34','quote',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('letters/ascii36','letters/ascii36','dollar\ sign',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('letters/ascii37','letters/ascii37','percent',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('letters/ascii38','letters/ascii38','ampersand',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('letters/ascii39','letters/ascii39','tick',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('letters/ascii40','letters/ascii40','open\ parenthesis',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('letters/ascii41','letters/ascii41','close\ parenthesis',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('letters/ascii42','letters/ascii42','star',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('letters/ascii44','letters/ascii44','comma',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('letters/ascii58','letters/ascii58','colon',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('letters/ascii59','letters/ascii59','semicolon',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('letters/ascii60','letters/ascii60','less\ than',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('letters/ascii62','letters/ascii62','greater\ than',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('letters/ascii63','letters/ascii63','question\ mark',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('letters/ascii91','letters/ascii91','left\ bracket',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('letters/ascii92','letters/ascii92','backslash',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('letters/ascii93','letters/ascii93','right\ bracket',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('letters/ascii94','letters/ascii94','caret',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('letters/ascii95','letters/ascii95','underscore',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('letters/ascii96','letters/ascii96','backtick',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('letters/asterisk','letters/asterisk','asterisk',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('letters/at','letters/at','at\ \[@\]',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('letters/b','letters/b','b',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('letters/c','letters/c','c',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('letters/dash','letters/dash','dash\ \[-\]',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('letters/d','letters/d','d',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('letters/dollar','letters/dollar','dollar\ \[\$\]',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('letters/dot','letters/dot','dot\ \[.\]',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('letters/e','letters/e','e',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('letters/equals','letters/equals','equals\ \[=\]',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('letters/exclaimation-point','letters/exclaimation-point','exclaimation-point\ \[\!\]',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('letters/f','letters/f','f',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('letters/g','letters/g','g',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('letters/h','letters/h','h',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('letters/i','letters/i','i',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('letters/j','letters/j','j',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('letters/k','letters/k','k',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('letters/l','letters/l','l',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('letters/m','letters/m','m',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('letters/n','letters/n','n',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('letters/o','letters/o','o',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('letters/plus','letters/plus','plus\ \[+\]',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('letters/p','letters/p','p',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('letters/q','letters/q','q',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('letters/r','letters/r','r',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('letters/slash','letters/slash','slash\ \[/\]',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('letters/space','letters/space','space\ \[\ \]',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('letters/s','letters/s','s',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('letters/t','letters/t','t',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('letters/u','letters/u','u',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('letters/v','letters/v','v',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('letters/w','letters/w','w',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('letters/x','letters/x','x',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('letters/y','letters/y','y',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('letters/zed','letters/zed','zed',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('letters/z','letters/z','z',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('location','location','Location.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('lowercase','lowercase','lowercase',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('minutes','minutes','minutes',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('number-not-answering','number-not-answering','The\ number\ is\ not\ answering.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('number','number','Number.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('num-was-successfully','num-was-successfully','The\ number\ was\ successfully...',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('one-moment-please','one-moment-please','One\ moment\,\ please.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('pbx-invalid','pbx-invalid','I\ am\ sorry\,\ that\'s\ not\ a\ valid\ extension.\ \ Please\ try\ again.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('pbx-invalidpark','pbx-invalidpark','I\ am\ sorry\,\ there\ is\ no\ call\ parked\ on\ that\ extension.\ \ Please\ try\ again.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('pbx-parkingfailed','pbx-parkingfailed','Parking\ attempt\ failed.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('pbx-transfer','pbx-transfer','Transfer.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('phonetic/9_p','phonetic/9_p','niner',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('phonetic/a_p','phonetic/a_p','alpha',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('phonetic/b_p','phonetic/b_p','bravo',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('phonetic/c_p','phonetic/c_p','charlie',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('phonetic/d_p','phonetic/d_p','delta',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('phonetic/e_p','phonetic/e_p','echo',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('phonetic/f_p','phonetic/f_p','foxtrot',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('phonetic/g_p','phonetic/g_p','golf',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('phonetic/h_p','phonetic/h_p','hotel',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('phonetic/i_p','phonetic/i_p','india',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('phonetic/j_p','phonetic/j_p','juliet',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('phonetic/k_p','phonetic/k_p','kilo',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('phonetic/l_p','phonetic/l_p','lima',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('phonetic/m_p','phonetic/m_p','mike',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('phonetic/n_p','phonetic/n_p','november',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('phonetic/o_p','phonetic/o_p','oscar',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('phonetic/p_p','phonetic/p_p','papa',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('phonetic/q_p','phonetic/q_p','quebec',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('phonetic/r_p','phonetic/r_p','romeo',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('phonetic/s_p','phonetic/s_p','sierra',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('phonetic/t_p','phonetic/t_p','tango',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('phonetic/u_p','phonetic/u_p','uniform',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('phonetic/v_p','phonetic/v_p','victor',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('phonetic/w_p','phonetic/w_p','whiskey',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('phonetic/x_p','phonetic/x_p','xray',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('phonetic/y_p','phonetic/y_p','yankee',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('phonetic/z_p','phonetic/z_p','zulu',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('please-try-again','please-try-again','Please\ try\ again.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('pls-hold-while-try','pls-hold-while-try','Please\ hold\ while\ we\ try\ to\ connect\ you.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('pls-try-call-later','pls-try-call-later','Please\ try\ your\ call\ again\ later.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('pm-invalid-option','pm-invalid-option','That\ option\ is\ invalid.\ Please\ try\ again.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('privacy-incorrect','privacy-incorrect','I\'m\ sorry\,\ that\ number\ is\ not\ valid.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('privacy-prompt','privacy-prompt','Please\ enter\ your\ phone\ number\,\ starting\ with\ the\ area\ code.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('privacy-thankyou','privacy-thankyou','Thank\ you.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('privacy-to-blacklist-last-caller','privacy-to-blacklist-last-caller','The\ last\ caller\ was...',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('privacy-unident','privacy-unident','The\ party\ you\ are\ trying\ to\ reach\ does\ not\ accept\ unidentified\ calls.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('priv-callee-options','priv-callee-options','Dial\ 1\ if\ you\ wish\ this\ caller\ to\ reach\ you\ directly\ now\,\ and\ in\ the\ future.\ \ Dial\ 2\ if\ you\ wish\ to\ send\ this\ caller\ to\ voicemail\ now\ and\ forevermore.\ \ Dial\ 3\ to\ send\ this\ caller\ to\ the\ torture\ menus\,\ now\ and\ forevermore.\ \ Dial\ 4\ to\ send\ this\ caller\ to\ a\ polite\ \"don\'t\ call\"\ menu\,\ now\ and\ forevermore.\ \ Dial\ 5\ to\ allow\ this\ caller\ to\ come\ straight\ thru\ to\ you\ in\ the\ future\,\ but\ just\ this\ once\,\ send\ them\ to\ voicemail.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('priv-introsaved','priv-introsaved','Thank\ you.\ Please\ hold\,\ while\ I\ attempt\ to\ connect\ you\ with\ your\ party\!',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('priv-recordintro','priv-recordintro','At\ the\ tone\,\ please\ say\ your\ name.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('queue-callswaiting','queue-callswaiting','Waiting\ to\ speak\ with\ a\ representative',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('queue-holdtime','queue-holdtime','The\ estimated\ hold\ time\ is\ currently',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('queue-less-than','queue-less-than','less\ than',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('queue-minute','queue-minute','minute',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('queue-minutes','queue-minutes','minutes',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('queue-periodic-announce','queue-periodic-announce','All\ of\ our\ represenatives\ are\ currently\ busy.\ Please\ stay\ on\ the\ line\ and\ your\ call\ will\ be\ answered\ by\ the\ next\ available\ representative.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('queue-quantity1','queue-quantity1','Currently\,\ there\ are\ more\ than\ ...',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('queue-quantity2','queue-quantity2','...\ callers\ waiting\ to\ speak\ with\ a\ representative.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('queue-reporthold','queue-reporthold','Hold\ time',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('queue-seconds','queue-seconds','Seconds',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('queue-thankyou','queue-thankyou','Thank\ you\ for\ your\ patience',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('queue-thereare','queue-thereare','You\ are\ currently\ caller\ number',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('queue-youarenext','queue-youarenext','Your\ call\ is\ now\ first\ in\ line\ and\ will\ be\ answered\ by\ the\ next\ available\ representative.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('removed','removed','Removed.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('screen-callee-options','screen-callee-options','Dial\ 1\ if\ you\ wish\ to\ immediately\ connect\ to\ the\ incoming\ call.\ \ Dial\ 2\ if\ you\ wish\ to\ send\ this\ caller\ to\ voicemail.\ \ Dial\ 3\ to\ send\ this\ caller\ to\ the\ torture\ menus.\ \ Dial\ 4\ to\ send\ this\ caller\ to\ a\ polite\ \"don\'t\ call\"\ menu.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('seconds','seconds','seconds',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('silence/10','silence/10','\(10\ seconds\ of\ silence\)',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('silence/1','silence/1','\(1\ second\ of\ silence\)',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('silence/2','silence/2','\(2\ seconds\ of\ silence\)',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('silence/3','silence/3','\(3\ seconds\ of\ silence\)',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('silence/4','silence/4','\(4\ seconds\ of\ silence\)',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('silence/5','silence/5','\(5\ seconds\ of\ silence\)',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('silence/6','silence/6','\(6\ seconds\ of\ silence\)',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('silence/7','silence/7','\(7\ seconds\ of\ silence\)',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('silence/8','silence/8','\(8\ seconds\ of\ silence\)',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('silence/9','silence/9','\(9\ seconds\ of\ silence\)',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('simul-call-limit-reached','simul-call-limit-reached','Simultaneous\ call\ limit\ reached.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('something-terribly-wrong','something-terribly-wrong','Something\ is\ terribly\ wrong\!',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('sorry','sorry','We\'re\ sorry.\ ',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('sorry-youre-having-problems','sorry-youre-having-problems','Sorry\ you\'re\ having\ problems.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('speed-dial-empty','speed-dial-empty','The\ speed\ dial\ entry\ you\'ve\ accessed\ is\ empty.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('speed-dial','speed-dial','Speed-dial.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('spy-agent','spy-agent','Agent',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('spy-console','spy-console','Console',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('spy-dahdi','spy-dahdi','DAHDI',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('spy-h323','spy-h323','H.323',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('spy-iax2','spy-iax2','does\ not\ say\ \"2\"\)',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('spy-iax','spy-iax','IAX',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('spy-jingle','spy-jingle','Jingle',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('spy-local','spy-local','Local',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('spy-mgcp','spy-mgcp','MGCP',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('spy-misdn','spy-misdn','M\ I\ S\ D\ N',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('spy-mobile','spy-mobile','Bluetooth\ Mobile',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('spy-nbs','spy-nbs','N\ B\ S',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('spy-sip','spy-sip','SIP',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('spy-skinny','spy-skinny','Skinny',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('spy-unistim','spy-unistim','Unistim',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('spy-usbradio','spy-usbradio','USB\ Radio',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('spy-zap','spy-zap','Zap',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('ss-noservice','ss-noservice','The\ number\ you\ have\ dialed\ is\ not\ in\ service.\ Please\ check\ the\ number\ and\ try\ again.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('telephone-number','telephone-number','Telephone\ number.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('time','time','Time.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('to-call-this-number','to-call-this-number','To\ call\ this\ number.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('to-extension','to-extension','To\ extension.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('to-listen-to-it','to-listen-to-it','To\ listen\ to\ it.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('to-rerecord-it','to-rerecord-it','To\ re-record\ it.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('transfer','transfer','Please\ hold\ while\ I\ try\ that\ extension.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('tt-allbusy','tt-allbusy','All\ representatives\ of\ the\ household\ are\ currently\ assisting\ other\ telemarketers.\ \ Please\ hold\ and\ your\ call\ will\ be\ answered\ in\ the\ order\ it\ was\ received.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('tt-monkeysintro','tt-monkeysintro','They\ have\ been\ carried\ away\ by\ monkeys',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('tt-somethingwrong','tt-somethingwrong','Something\ is\ terribly\ wrong',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('tt-weasels','tt-weasels','Weasels\ have\ eaten\ our\ phone\ system',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('unidentified-no-callback','unidentified-no-callback','Un-indentified\ or\ witheld\ and\ therefore\ cannot\ be\ called\ back.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('uppercase','uppercase','uppercase',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-advopts','vm-advopts','press\ 3\ for\ advanced\ options',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-and','vm-and','and',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-calldiffnum','vm-calldiffnum','press\ 2\ to\ enter\ a\ different\ number',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-changeto','vm-changeto','Change\ to\ which\ folder\?',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-Cust1','vm-Cust1','folder\ 5',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-Cust2','vm-Cust2','folder\ 6',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-Cust3','vm-Cust3','folder\ 7',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-Cust4','vm-Cust4','folder\ 8',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-Cust5','vm-Cust5','folder\ 9',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-deleted','vm-deleted','Message\ deleted.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-delete','vm-delete','Press\ 7\ to\ delete\ this\ message.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-dialout','vm-dialout','please\ wait\ while\ i\ connect\ your\ call',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-duration','vm-duration','This\ message\ lasts\ ...',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-enter-num-to-call','vm-enter-num-to-call','please\ enter\ the\ number\ you\ wish\ to\ call',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-extension','vm-extension','extension',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-Family','vm-Family','family',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-first','vm-first','first',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-for','vm-for','for',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-forward-multiple','vm-forward-multiple','press\ 1\ to\ send\ this\ message\,\ or\ 2\ to\ add\ another\ recipient.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-forwardoptions','vm-forwardoptions','press\ 1\ to\ prepend\ a\ message\ or\ 2\ to\ forward\ the\ message\ without\ prepending',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-forward','vm-forward','Press\ 1\ to\ enter\ an\ extension\,\ press\ 2\ to\ use\ the\ directory',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-Friends','vm-Friends','friends',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-from-extension','vm-from-extension','message\ from\ extension',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-from','vm-from','from',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-from-phonenumber','vm-from-phonenumber','message\ from\ phone\ number',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-goodbye','vm-goodbye','Goodbye',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-helpexit','vm-helpexit','Press\ star\ for\ help\ or\ pound\ to\ exit.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-INBOX','vm-INBOX','new',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-incorrect','vm-incorrect','Login\ incorrect.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-incorrect-mailbox','vm-incorrect-mailbox','Login\ incorrect.\ \ Mailbox\?',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-instructions','vm-instructions','To\ look\ into\ your\ messages\ press\ 1\ now.\ \ You\ may\ quit\ voicemail\ at\ any\ time\ by\ pressing\ the\ pound\ key.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-intro','vm-intro','Please\ leave\ your\ message\ after\ the\ tone.\ \ When\ done\ hang\ up\ or\ press\ the\ pound\ key.\ \(simple\ tone\ sound\ plays\)',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-invalidpassword','vm-invalidpassword','That\ is\ not\ a\ valid\ password.\ \ Please\ try\ again.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-invalid-password','vm-invalid-password','That\ password\ does\ not\ meet\ the\ minimum\ requirements\ for\ this\ mailbox.\ \ Please\ try\ again.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-isonphone','vm-isonphone','is\ on\ the\ phone',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-isunavail','vm-isunavail','is\ unavailable',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-last','vm-last','last',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-leavemsg','vm-leavemsg','Press\ 5\ to\ leave\ a\ message',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-login','vm-login','Comedian\ Mail.\ \ Mailbox\?',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-mailboxfull','vm-mailboxfull','sorry\ but\ the\ user\'s\ mail\ box\ can\'t\ accept\ more\ messages',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-marked-nonurgent','vm-marked-nonurgent','Urgent\ status\ removed.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-marked-urgent','vm-marked-urgent','Message\ marked\ urgent.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-message','vm-message','message',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-messages','vm-messages','messages',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-minutes','vm-minutes','minutes',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-mismatch','vm-mismatch','The\ passwords\ you\ entered\ and\ re-entered\ did\ not\ match.\ \ Please\ try\ again.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-msgforwarded','vm-msgforwarded','Your\ message\ has\ been\ successfully\ forwarded.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-msginstruct','vm-msginstruct','To\ hear\ the\ next\ message\ press\ 6\,\ to\ repeat\ this\ message\ press\ 5\,\ to\ hear\ the\ previous\ message\ press\ 4\,\ to\ delete\ or\ undelete\ this\ message\ press\ zero\,\ to\ quit\ voicemail\ press\ pound.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-msgsaved','vm-msgsaved','Your\ message\ has\ been\ saved.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-newpassword','vm-newpassword','Please\ enter\ your\ new\ password\ followed\ by\ the\ pound\ key.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-newuser','vm-newuser','Welcome\ to\ Comedian\ Mail.\ First\,\ I\ will\ guide\ you\ through\ a\ short\ setup\ process.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-next','vm-next','Press\ 6\ to\ play\ the\ next\ message.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-nobodyavail','vm-nobodyavail','Nobody\ is\ available\ to\ take\ your\ call\ at\ the\ moment',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-nobox','vm-nobox','you\ cannot\ reply\ to\ this\ message\ because\ the\ sender\ does\ not\ have\ a\ mailbox',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-nomore','vm-nomore','No\ more\ messages.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-no','vm-no','no',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-nonumber','vm-nonumber','I\'m\ afraid\ i\ don\'t\ know\ who\ sent\ this\ message',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-num-i-have','vm-num-i-have','the\ number\ i\ have\ is',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-Old','vm-Old','old',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-onefor-full','vm-onefor-full','Press\ one\ to\ listen\ to\ ...',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-onefor','vm-onefor','Press\ 1\ for',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-options','vm-options','Press\ 1\ to\ record\ your\ unavailable\ message\,\ press\ 2\ to\ record\ your\ busy\ message\,\ press\ 3\ to\ record\ your\ name\,\ press\ 4\ to\ record\ your\ temporary\ greeting\,\ press\ 5\ to\ change\ your\ password\,\ press\ star\ to\ return\ to\ the\ main\ menu.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-opts-full','vm-opts-full','press\ 2\ to\ access\ messages\ saved\ in\ other\ folders.\ \ Press\ 3\ to\ record\ a\ message\ for\ another\ mailbox.\ \ Press\ 0\ for\ greetings\ and\ password\ management.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-opts','vm-opts','Press\ 2\ to\ change\ folders\,\ press\ 3\ for\ advanced\ options\,\ press\ zero\ for\ mailbox\ options.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-passchanged','vm-passchanged','Your\ passwords\ have\ been\ changed.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-password','vm-password','password',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-pls-try-again','vm-pls-try-again','please\ try\ again',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-press','vm-press','press',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-prev','vm-prev','Press\ 4\ for\ the\ previous\ message',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-reachoper','vm-reachoper','press\ 0\ to\ reach\ an\ operator',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-rec-busy','vm-rec-busy','After\ the\ tone\ say\ your\ busy\ message\ and\ then\ press\ the\ pound\ key.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-received','vm-received','received',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-rec-name','vm-rec-name','After\ the\ tone\ say\ your\ name\ and\ then\ press\ the\ pound\ key.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-record-prepend','vm-record-prepend','At\ the\ tone\,\ please\ record\ an\ introduction\ to\ the\ forwarded\ message.\ \ When\ done\,\ press\ the\ pound\ sign.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-rec-temp','vm-rec-temp','After\ the\ tone\,\ say\ your\ temporary\ message\,\ and\ then\ press\ the\ pound\ key.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-rec-unv','vm-rec-unv','After\ the\ tone\ say\ your\ unavailable\ message\ and\ then\ press\ the\ pound\ key.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-reenterpassword','vm-reenterpassword','Please\ re-enter\ your\ password\ followed\ by\ the\ pound\ key.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-repeat','vm-repeat','Press\ 5\ to\ repeat\ the\ current\ message.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-review-nonurgent','vm-review-nonurgent','Press\ 4\ to\ remove\ the\ urgent\ status\ of\ this\ message.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-review','vm-review','press\ 1\ to\ accept\ this\ recording\ press\ 2\ to\ listen\ to\ it\ press\ 3\ to\ rerecord\ your\ message',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-review-urgent','vm-review-urgent','Press\ 4\ to\ mark\ this\ message\ as\ urgent.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-saved','vm-saved','saved',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-savedto','vm-savedto','saved\ to',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-savefolder','vm-savefolder','Which\ folder\ should\ I\ save\ the\ message\ to\?',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-savemessage','vm-savemessage','or\ 9\ to\ save\ this\ message',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-saveoper','vm-saveoper','press\ 1\ to\ accept\ this\ recording\,\ otherwise\,\ please\ continue\ to\ hold',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-sorry','vm-sorry','I\'m\ sorry\ I\ did\ not\ understand\ your\ response.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-star-cancel','vm-star-cancel','press\ star\ to\ cancel',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-starmain','vm-starmain','press\ star\ to\ return\ to\ the\ main\ menu',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-tempgreetactive','vm-tempgreetactive','Your\ temporary\ greeting\ is\ currently\ active',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-tempgreeting2','vm-tempgreeting2','press\ 1\ to\ record\ your\ temporary\ greeting\,\ or\ press\ 2\ to\ erase\ your\ temporary\ greeting',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-tempgreeting','vm-tempgreeting','press\ 1\ to\ record\ your\ temporary\ greeting',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-tempremoved','vm-tempremoved','Your\ temporary\ greeting\ has\ been\ removed',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-then-pound','vm-then-pound','then\ press\ pound',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-theperson','vm-theperson','The\ person\ at\ extension',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-tmpexists','vm-tmpexists','There\ is\ a\ temporary\ greeting\,\ which\ overrides\ your\ standard\ greetings.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-tocallback','vm-tocallback','press\ 2\ to\ call\ the\ person\ who\ sent\ this\ message',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-tocallnum','vm-tocallnum','press\ 1\ to\ call\ this\ number',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-tocancelmsg','vm-tocancelmsg','press\ star\ to\ cancel\ this\ message',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-tocancel','vm-tocancel','or\ pound\ to\ cancel.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-toenternumber','vm-toenternumber','press\ 1\ to\ enter\ a\ number',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-toforward','vm-toforward','Press\ 8\ to\ forward\ the\ message\ to\ another\ user',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-tohearenv','vm-tohearenv','press\ 3\ to\ hear\ the\ message\ envelope',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-tomakecall','vm-tomakecall','press\ 4\ to\ place\ an\ outgoing\ call',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-tooshort','vm-tooshort','your\ message\ is\ too\ short\ ',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-toreply','vm-toreply','press\ 1\ to\ send\ a\ reply',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-torerecord','vm-torerecord','press\ 3\ to\ rerecord\ your\ message',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-undeleted','vm-undeleted','Message\ undeleted.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-undelete','vm-undelete','Press\ 7\ to\ undelete\ this\ message',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-unknown-caller','vm-unknown-caller','from\ an\ unknown\ caller',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-Urgent','vm-Urgent','urgent',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-whichbox','vm-whichbox','To\ leave\ a\ message\,\ please\ enter\ a\ mailbox\ number.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-Work','vm-Work','work',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('vm-youhave','vm-youhave','you\ have',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('with','with','With.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('you-entered','you-entered','You\ entered.',0,'en');
INSERT INTO `recordings` (`displayname`,`filename`,`description`,`fcode`,`fcode_pass`) values ('your','your','Your.',0,'en');
